<a href="https://colab.research.google.com/github/sawsanzaky/Course-Data-Analysis-/blob/main/Python_DataAnalysis_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

NumPy library is one of the fundamental packages for scientific computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures. It is widely used in data science, machine learning, and scientific computing due to its high performance and ease of use

**Key Features of NumPy:**
N-dimensional array (ndarray): NumPy introduces the ndarray (n-dimensional array), which is a powerful data structure that allows for efficient storage and manipulation of numerical data.

Example:

In [1]:
import numpy as np

# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # Output: [1 2 3 4 5]

# Creating a 2D array (matrix)
arr2d = np.array([[1, 2], [3, 4]])
print(arr2d)  # Output: [[1 2]
              #          [3 4]]


[1 2 3 4 5]
[[1 2]
 [3 4]]


In [2]:
arr = np.array([1, 2, 3, 4])
print(arr * 2)  # Output: [2 4 6 8]
print(arr + 5)  # Output: [6 7 8 9]


[2 4 6 8]
[6 7 8 9]


In [3]:
arr = np.array([1, 2, 3])
print(np.sin(arr))  # Output: [0.84147098 0.90929743 0.14112001]
print(np.log(arr))  # Output: [0.         0.69314718 1.09861229]


[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]


In [4]:
arr = np.array([1, 2, 3])
scalar = 10
print(arr + scalar)  # Output: [11 12 13]


[11 12 13]


In [5]:
arr = np.array([1, 2, 3, 4, 5])

# Accessing specific elements
print(arr[0])  # Output: 1

# Slicing (selecting a range of elements)
print(arr[1:4])  # Output: [2 3 4]


1
[2 3 4]


**Linear Algebra**: NumPy contains functions to perform matrix operations, including dot products, matrix multiplication, determinant calculation, etc.

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))  # Matrix multiplication


[[19 22]
 [43 50]]


In [7]:
rand_array = np.random.rand(3, 3)  # 3x3 array of random numbers between 0 and 1
print(rand_array)

random_int = np.random.randint(1, 10, 5)  # 5 random integers between 1 and 10
print(random_int)


[[0.82617882 0.6573338  0.1366152 ]
 [0.42428349 0.68474165 0.60595055]
 [0.43921893 0.30894506 0.87361799]]
[8 2 6 2 2]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr_reshaped = arr.reshape(2, 3)
print(arr_reshaped)


[[1 2 3]
 [4 5 6]]


In [9]:
data = np.array([1, 2, 3, 4, 5])
print(np.mean(data))  # Output: 3.0
print(np.median(data))  # Output: 3.0


3.0
3.0


In [10]:
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))  # Output: 15
print(np.mean(arr))  # Output: 3.0
print(np.max(arr))  # Output: 5
print(np.min(arr))  # Output: 1


15
3.0
5
1


In [11]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated = np.concatenate([arr1, arr2])  # [1 2 3 4 5 6]
